// ============================================================================
// FMP-ready PAI Data File — SFDR 2022/1288 Annex I Table 1 mirror
// (v0.5.0-alpha.6 — Phase 1, commit 1.4)
// ============================================================================
//
// The F8 deliverable from the May 2026 pressure-test. PB's differentiation
// from Big 4 SPO providers is not narrative quality; it is producing the
// FMP-ready structured deliverable (machine-readable PAI data, structured
// evidence pack, verdict cells) as a first-class output alongside the
// narrative. This file makes that claim true at the code level.
//
// Schema is identical to SFDR 2022/1288 Annex I Table 1 (mandatory indicators).
// Structural identity with the regulation — not a PB schema that maps to it.
// Drop-in for FMP ingestion into existing Art 9 fund PAI portfolio integration.
//
// Row set: PAIs 1, 2, 4, 5, 7, 8, 9, 10, 11, 13 — ten mandatory indicators
// relevant to data-centre projects. PAI 4 (fossil-fuel sector exposure) is
// always emitted as `not_applicable` for DC projects, never omitted —
// drop-in-ready for FMP ingestion requires structural completeness.
//
// No new input collection. Every field derives from existing v3.5 evidence
// inputs on ProjectInput.sfdr (DNSH evidence, Art 9 PAI data) and
// EntityInput.sfdr (governance, PAI disclosures).
// ============================================================================

import type { EngineRun } from "../engine";
import type {
  ProjectDNSHEvidence,
  Art9PAIDataInputs,
  ProjectPAIDatum,
  AssuranceTier,
} from "../sfdr/types";

export interface PAIDataFile {
  schema_source: "SFDR_2022_1288_Annex_I_Table_1";
  reporting_period: string;
  rows: PAIRow[];
}

export type VerificationStatus =
  | "third_party_assured"
  | "management_attested"
  | "unverified"
  | "not_applicable";

export interface PAIRow {
  pai_number: number;
  indicator_name: string;
  metric_definition: string;
  value: number | string | null;
  unit: string;
  data_source: string;
  methodology_note: string;
  verification_status: VerificationStatus;
  applicability: "applicable" | "not_applicable";
  applicability_rationale?: string;
  data_unavailable_rationale?: string;
}

// Source of truth for the per-PAI Annex I labels. Wording mirrors the
// published regulation (Commission Delegated Regulation (EU) 2022/1288,
// Annex I, Table 1 — mandatory indicators).
const PAI_SCHEMA: Record<number, { indicator_name: string; metric_definition: string; unit: string }> = {
  1: {
    indicator_name: "GHG emissions",
    metric_definition: "Scope 1, Scope 2, Scope 3 and total GHG emissions of investee companies (tonnes CO2-equivalent)",
    unit: "tCO2e",
  },
  2: {
    indicator_name: "Carbon footprint",
    metric_definition: "Carbon footprint of investments (tonnes CO2-equivalent per EUR million invested)",
    unit: "tCO2e/EURm",
  },
  4: {
    indicator_name: "Exposure to companies active in the fossil fuel sector",
    metric_definition: "Share of investments in investee companies active in the fossil fuel sector",
    unit: "%",
  },
  5: {
    indicator_name: "Share of non-renewable energy consumption and production",
    metric_definition: "Share of non-renewable energy consumption and non-renewable energy production of investee companies from non-renewable energy sources compared to renewable energy sources, expressed as a percentage of total energy sources",
    unit: "%",
  },
  7: {
    indicator_name: "Activities negatively affecting biodiversity-sensitive areas",
    metric_definition: "Share of investments in investee companies with sites/operations located in or near to biodiversity-sensitive areas where activities of those investee companies negatively affect those areas",
    unit: "%",
  },
  8: {
    indicator_name: "Emissions to water",
    metric_definition: "Tonnes of emissions to water generated by investee companies per EUR million invested, expressed as a weighted average",
    unit: "tonnes/EURm",
  },
  9: {
    indicator_name: "Hazardous waste and radioactive waste ratio",
    metric_definition: "Tonnes of hazardous waste and radioactive waste generated by investee companies per EUR million invested, expressed as a weighted average",
    unit: "tonnes/EURm",
  },
  10: {
    indicator_name: "Violations of UN Global Compact principles and OECD Guidelines for Multinational Enterprises",
    metric_definition: "Share of investments in investee companies that have been involved in violations of the UNGC principles or OECD Guidelines for Multinational Enterprises",
    unit: "%",
  },
  11: {
    indicator_name: "Lack of processes and compliance mechanisms to monitor compliance with UN Global Compact principles and OECD Guidelines for Multinational Enterprises",
    metric_definition: "Share of investments in investee companies without policies to monitor compliance with the UNGC principles or OECD Guidelines for Multinational Enterprises or grievance/complaints handling mechanisms to address violations",
    unit: "%",
  },
  13: {
    indicator_name: "Board gender diversity",
    metric_definition: "Average ratio of female to male board members in investee companies, expressed as a percentage of all board members",
    unit: "%",
  },
};

const PAI_ROW_ORDER: readonly number[] = [1, 2, 4, 5, 7, 8, 9, 10, 11, 13];

export function buildPAIDataFile(run: EngineRun): PAIDataFile {
  const dnsh = run.project_input.sfdr?.dnsh?.evidence;
  const art9pai = run.project_input.sfdr?.art9?.pai_data;
  // Entity-level data (governance for board diversity, UNGC) — accessed
  // defensively because the engine doesn't carry EntityInput through to the
  // run object; renderers that need entity-level PAI fields source them
  // from the project DNSH evidence shadow (which the v3.5 scoring functions
  // accept as the authoritative project-level signal for c4 PAIs 10/11/13).
  const ep = run.project_input.sfdr?.art9?.evidence_pack;
  const tier = ep?.assurance_tier;

  const rows: PAIRow[] = PAI_ROW_ORDER.map((n) =>
    buildRow(n, dnsh, art9pai, tier),
  );

  return {
    schema_source: "SFDR_2022_1288_Annex_I_Table_1",
    reporting_period: derivePeriod(art9pai, dnsh),
    rows,
  };
}

function buildRow(
  n: number,
  dnsh: ProjectDNSHEvidence | undefined,
  art9pai: Art9PAIDataInputs | undefined,
  tier: AssuranceTier | undefined,
): PAIRow {
  const schema = PAI_SCHEMA[n];

  // PAI 4 — almost always not_applicable for DC projects. Emit row anyway.
  if (n === 4) {
    return {
      pai_number: 4,
      indicator_name: schema.indicator_name,
      metric_definition: schema.metric_definition,
      value: null,
      unit: schema.unit,
      data_source: "n/a",
      methodology_note: "Data-centre activity classification (NACE J63.11) does not fall within the fossil-fuel sector definition under SFDR 2022/1288.",
      verification_status: "not_applicable",
      applicability: "not_applicable",
      applicability_rationale:
        "Data-centre infrastructure projects do not have fossil-fuel sector exposure under the Annex I definition; PAI 4 is emitted for FMP-ingestion completeness but does not apply.",
    };
  }

  // Prefer Art 9 PAI data when explicitly provided; otherwise derive from
  // DNSH evidence; otherwise null with rationale.
  const datum = art9pai?.per_pai?.[String(n)];
  if (datum?.value !== undefined && datum.value !== null) {
    return {
      pai_number: n,
      indicator_name: schema.indicator_name,
      metric_definition: schema.metric_definition,
      value: datum.value,
      unit: datum.unit ?? schema.unit,
      data_source: "Project disclosure (Art 9 PAI data file)",
      methodology_note: datum.methodology_ref ?? "",
      verification_status: deriveVerificationStatus(datum, tier),
      applicability: "applicable",
    };
  }

  const derived = deriveFromDNSH(n, dnsh);
  if (derived !== null) {
    return {
      pai_number: n,
      indicator_name: schema.indicator_name,
      metric_definition: schema.metric_definition,
      value: derived.value,
      unit: derived.unit ?? schema.unit,
      data_source: derived.data_source,
      methodology_note: derived.methodology_note,
      verification_status: tier ? deriveVerificationStatusFromTier(tier) : "unverified",
      applicability: "applicable",
    };
  }

  return {
    pai_number: n,
    indicator_name: schema.indicator_name,
    metric_definition: schema.metric_definition,
    value: null,
    unit: schema.unit,
    data_source: "n/a",
    methodology_note: "",
    verification_status: "unverified",
    applicability: "applicable",
    data_unavailable_rationale: dataUnavailableRationale(n, dnsh, art9pai),
  };
}

// Maps DNSH evidence onto a per-PAI value when the developer hasn't supplied
// an explicit Art 9 PAI data file but the DNSH inputs carry the relevant
// signal. The signals chosen here are conservative and one-to-one with
// values FMP analysts would expect to ingest; multi-signal composites are
// deferred to the narrative report so the FMP CSV stays auditable.
interface DerivedPAI {
  value: number | string;
  unit?: string;
  data_source: string;
  methodology_note: string;
}

function deriveFromDNSH(n: number, dnsh: ProjectDNSHEvidence | undefined): DerivedPAI | null {
  if (!dnsh) return null;
  switch (n) {
    case 1:
    case 2: {
      // GHG-related: surface PPA coverage as the strongest project-level
      // signal when no direct PAI 1/2 value is provided. FMP analysts treat
      // PPA coverage as a leading-indicator proxy for project-level Scope 2
      // intensity, with the caveat noted in methodology_note.
      if (dnsh.renewable_ppa_coverage_percent !== undefined) {
        return {
          value: dnsh.renewable_ppa_coverage_percent,
          unit: "% PPA coverage (proxy)",
          data_source: "Project DNSH evidence — renewable PPA coverage",
          methodology_note: `PAI ${n} surrogate: renewable PPA coverage as a leading-indicator proxy. Direct PAI ${n} value not supplied in Art 9 PAI data file.`,
        };
      }
      return null;
    }
    case 5: {
      if (dnsh.renewable_tier !== undefined) {
        const value = dnsh.renewable_tier === 1 || dnsh.renewable_tier === 2 ? 0 : 100;
        return {
          value,
          unit: "% non-renewable (proxy)",
          data_source: "Project DNSH evidence — renewable tier classification",
          methodology_note: `Tier ${dnsh.renewable_tier} renewable sourcing classified as ${value === 0 ? "renewable-dominant" : "non-renewable-dominant"} for the PAI 5 proxy. Direct PAI 5 value not supplied in Art 9 PAI data file.`,
        };
      }
      return null;
    }
    case 7: {
      // Tier 1 KBA buffer path: signal whether project is in/near a KBA.
      // Tier 2 TNFD LEAP path: signal the LEAP risk finding.
      if (dnsh.biodiversity_assessment_type === "tnfd_leap" && dnsh.tnfd_leap_risk_level) {
        return {
          value: dnsh.tnfd_leap_risk_level,
          unit: "TNFD LEAP risk level",
          data_source: "Project DNSH evidence — TNFD LEAP assessment (Tier 2)",
          methodology_note: "v3.5 PAI 7 evidence accepts TNFD LEAP findings as Tier 2 alongside the KBA-buffer Tier 1 measurement.",
        };
      }
      if (dnsh.distance_to_biodiversity_sensitive_area_km !== undefined) {
        const inBuffer = dnsh.distance_to_biodiversity_sensitive_area_km <= 2;
        return {
          value: inBuffer ? "yes" : "no",
          unit: "negative-effect flag",
          data_source: "Project DNSH evidence — KBA buffer measurement (Tier 1)",
          methodology_note: `Distance to nearest biodiversity-sensitive area: ${dnsh.distance_to_biodiversity_sensitive_area_km} km. Inside 2km KBA buffer: ${inBuffer ? "yes" : "no"}.`,
        };
      }
      return null;
    }
    case 8: {
      if (dnsh.wue_value !== undefined) {
        return {
          value: dnsh.wue_value,
          unit: "L/kWh WUE (proxy)",
          data_source: "Project DNSH evidence — water usage effectiveness",
          methodology_note: "PAI 8 surrogate: site-level WUE as the closest project-level analog to the Annex I 'emissions to water' indicator for data-centre water consumption. Direct PAI 8 value not supplied in Art 9 PAI data file.",
        };
      }
      return null;
    }
    case 9: {
      if (dnsh.it_hardware_recovery_rate !== undefined) {
        return {
          value: (1 - dnsh.it_hardware_recovery_rate) * 100,
          unit: "% IT hardware to non-recovery streams (proxy)",
          data_source: "Project DNSH evidence — IT hardware recovery rate",
          methodology_note: `Recovery rate ${(dnsh.it_hardware_recovery_rate * 100).toFixed(0)}%; complement reported as the PAI 9 proxy. Direct PAI 9 value not supplied in Art 9 PAI data file.`,
        };
      }
      return null;
    }
    case 10:
    case 11: {
      if (dnsh.ungc_violations_5yr_count !== undefined) {
        return {
          value: dnsh.ungc_violations_5yr_count,
          unit: "violations (5-year lookback)",
          data_source: "Project DNSH evidence — UNGC violation count",
          methodology_note: `Number of UNGC violations within the 5-year lookback window. PAI ${n} reported at the developer-investee level.`,
        };
      }
      return null;
    }
    case 13: {
      if (dnsh.board_women_percent !== undefined) {
        return {
          value: dnsh.board_women_percent,
          unit: "% women on board",
          data_source: "Project DNSH evidence — board diversity",
          methodology_note: "Developer-entity board gender diversity, used as the project-level PAI 13 value (PB scores SFDR for the developer-investee).",
        };
      }
      return null;
    }
    default:
      return null;
  }
}

function deriveVerificationStatus(
  datum: ProjectPAIDatum,
  tier: AssuranceTier | undefined,
): VerificationStatus {
  if (datum.third_party_verified) return "third_party_assured";
  if (tier === "reasonable_big4" || tier === "limited_big4") {
    return "third_party_assured";
  }
  if (tier === "limited_partial") return "third_party_assured";
  if (tier === "management_only") return "management_attested";
  return "unverified";
}

function deriveVerificationStatusFromTier(tier: AssuranceTier): VerificationStatus {
  switch (tier) {
    case "reasonable_big4":
    case "limited_big4":
    case "limited_partial":
      return "third_party_assured";
    case "management_only":
      return "management_attested";
  }
}

function dataUnavailableRationale(
  n: number,
  dnsh: ProjectDNSHEvidence | undefined,
  art9pai: Art9PAIDataInputs | undefined,
): string {
  if (!dnsh && !art9pai) {
    return `No project-level DNSH evidence or Art 9 PAI data file supplied. PAI ${n} cannot be populated for the FMP ingestion file.`;
  }
  return `PAI ${n} value not supplied in Art 9 PAI data file and no DNSH evidence signal available to derive a proxy. Recommended to obtain the indicator directly from the developer's ESG disclosures or commission measurement.`;
}

function derivePeriod(
  art9pai: Art9PAIDataInputs | undefined,
  dnsh: ProjectDNSHEvidence | undefined,
): string {
  // Prefer Art 9 explicit recency; otherwise default to "current reporting
  // period" — the field is informational on the FMP CSV header and is not
  // load-bearing for scoring.
  if (art9pai?.data_recency_months !== undefined) {
    return `Reporting period ending within last ${art9pai.data_recency_months} months`;
  }
  // dnsh is intentionally unused for period derivation; the DNSH evidence
  // does not carry a measurement period field today. Hook kept so future
  // additions (e.g. operational_year) have a clear place to land.
  void dnsh;
  return "Current reporting period";
}
